### ISSUE TITLE
Diacritics too light in 6pt Master

### ISSUE THREAD

**Issue by agyeiarcher** [agyeiarcher/Jaro#10]
Diacritics should get punchier to be readable at smaller sizes, not stay the same relative size. 

I added scale suggestions in pink to /grave, /ogonek, and /circumflex

![Screenshot 2023-12-17 at 11 35 14 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/b2b630db-956c-42f8-87a3-9a8b57b6b0b4)
before ☝🏿

![Screenshot 2023-12-17 at 11 29 20 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/da3c4c11-4290-4aa5-a208-59f17392daaf)
my suggestion ☝🏿

**Comment by bghryct** [comment]
working on this.
