### ISSUE TITLE
Outstrokes on /e, /y, /c in 6pt Master

### ISSUE THREAD

**Issue by agyeiarcher** [agyeiarcher/Jaro#11]
Noticed this while checking through combo glyphs. Good to check on; maybe simplify number of points for easier interpolation? Should match the 72pt outstrokes' straightness

![Screenshot 2023-12-17 at 11 39 42 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/74d18fae-5ea4-4e65-a7b5-448f052a66e3)

![Screenshot 2023-12-17 at 11 39 55 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/ec37a6b1-df24-4317-a5e3-dfc2f2b2e1df)

**Comment by bghryct** [comment]
these are included for clarity at small sizes. The angles appear nasty without the "bent" strokes.
