### ISSUE TITLE
Resolve inside joins

### ISSUE THREAD

**Issue by agyeiarcher** [agyeiarcher/Jaro#12]
These seem a bit varied where they could be more consistent, esp given the visibility at 72pt. Maybe better all square, or a predictable combo of square and round

![Screenshot 2023-12-17 at 11 28 23 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/ac9ac93a-ab7b-4cfa-9d84-5fa35a2b13eb)
![Screenshot 2023-12-17 at 11 29 05 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/a9e87bdb-326e-495d-b2b1-0d9a6efef974)
![Screenshot 2023-12-17 at 11 31 00 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/3d78af9f-8ed3-42c7-b81c-9f4d8af72fc1)
![Screenshot 2023-12-17 at 11 32 18 PM](https://github.com/agyeiarcher/Jaro/assets/34943654/76ae12f1-2125-4959-a784-3c764d272b3c)

**Comment by bghryct** [comment]
I've applied it to the y where I think it's most appropriate.

**Comment by bghryct** [comment]
should be complete now.
